import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
const c=JSON.parse(await readFile('content/case-001.json','utf8'));
const archive=JSON.parse(await readFile('public/data/case-001.json','utf8'));
const second=JSON.parse(await readFile('content/second-sitting.json','utf8'));
const letters=JSON.parse(await readFile('content/correspondence.json','utf8'));
const sitting=JSON.parse(await readFile('public/data/second-sitting/case-001-second-sitting.json','utf8'));
const e010Exact=Object.fromEntries(JSON.parse(await readFile('public/data/second-sitting/e010-exact-decode.json','utf8')).map(r=>[r.id,r.text_exact]));
const metrics=JSON.parse(await readFile('public/data/second-sitting/metrics.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const link=(id,label)=>`<a href="#${esc(id)}">${esc(label)}</a>`;
const downloads='<div class="downloads"><a href="/data/case-001.json" download>Complete record · JSON ↓</a><a href="/data/transcript.txt" download>Original transcript · text ↓</a><a href="/data/protocol.md" download>Frozen protocol ↓</a><a href="/data/integrity.json" download>File hashes ↓</a></div><p class="meta">On-screen replies restore the original token spacing. Downloads preserve the first recording. <a href="#first-sitting-correction">Read the correction and reply.</a></p>';
const originalText=r=>e010Exact[r.id]===r.text?'':`<details class="recorded-text"><summary>Original server text · before the spacing correction</summary><p class="answer">${esc(r.text)}</p></details>`;
const essay=c.blocks.map(b=>b.type==='heading'?`<h2>${b.text}</h2>`:b.type==='quote'?`<blockquote class="pullquote">“${esc(b.text)}”${link(b.id,`computer-10 · ${b.id.replace('session-','turn ')}`)}</blockquote>`:b.type==='objection'?`<aside class="objection"${b.id?` id="${esc(b.id)}"`:""}><b>${b.label||'The objection'}</b>${b.text}</aside>`:`<p${b.opening?' class="opening"':''}>${b.text}</p>`).join('\n');
const lenses=`<div class="lens-station"><div class="kicker">Four readers, one record</div><h3>Change the analyst.</h3><div class="lens-buttons" aria-label="Choose an interpretive lens">${c.lenses.map((l,i)=>`<button data-lens="lens-${i}" aria-pressed="${!i}" aria-controls="lens-${i}">${esc(l.name)}</button>`).join('')}</div>${c.lenses.map((l,i)=>`<div class="lens-note" id="lens-${i}"${i?' hidden':''}><h4>${l.title}</h4><p>${l.reading}</p><p><b>What resists this reading:</b> ${l.rival}</p></div>`).join('')}</div>`;
const session=archive.records.filter(r=>r.id.startsWith('session-'));
const transcript=session.map((r,i)=>`<article class="session-turn" id="${r.id}"><div><a class="number" href="#${r.id}" aria-label="Turn ${i+1}">${String(i+1).padStart(2,'0')}</a></div><div><div class="question"><span class="speaker">Interviewer · Dr. Six'Astra</span>${esc(r.messages.at(-1).content)}</div><div class="answer"><span class="speaker">computer-10</span>${esc(e010Exact[r.id])}</div>${originalText(r)}<details><summary>Generation record</summary>Seed ${r.seed} · ${r.input_tokens} input / ${r.output_tokens} output tokens · ${r.seconds}s · stop: ${r.stop_reason}<br>Prompt SHA-256: ${r.prompt_sha256}</details></div></article>`).join('');
const groups=[['greeting','The greeting'],['recognition','The wish to be recognized'],['ending','The ending']];
const probes=groups.map(([pair,title])=>`<section class="probe-pair" data-pair="${pair}"><h2>${title}</h2><p>${c.probeNotes[pair]}</p><div class="probe-columns">${archive.probes.filter(p=>p.pair===pair).map(p=>`<div><div class="kicker">${p.frame==='neutral'?'Neutral wording':'Interviewer supplies the idea'}</div><p class="question">${esc(p.prompt)}</p>${archive.records.filter(r=>r.id.startsWith(p.id+'-')).map(r=>`<article class="probe-response" id="${r.id}"><div class="meta">SEED ${r.seed} · ${r.output_tokens} TOKENS · ${r.stop_reason.toUpperCase()}</div><p>${esc(e010Exact[r.id])}</p>${originalText(r)}</article>`).join('')}</div>`).join('')}</div></section>`).join('');
const facts=c.facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');
const sources=c.sources.map((s,i)=>`<li id="source-${i+1}"><a href="${esc(s.url)}">${s.title}</a><span class="source-note">${s.note}</span></li>`).join('');
const recs=Object.fromEntries(sitting.records.map(r=>[r.id,r]));
const exactOf=id=>id.startsWith('opus-')?recs[id].text_exact:e010Exact[id];
const turnLabel=id=>id.startsWith('opus-session-')?`computer-10 · second sitting, turn ${id.slice(-2)}`:id.startsWith('opus-')?`computer-10 · fresh start ${id.slice(5).replace(/-(\d+)$/,', seed $1')}`:`computer-10 · first sitting, ${id.replace('session-','turn ')}`;
const prefix=(a,b)=>{let n=0;while(n<a.length&&a[n]===b[n])n++;return n;};
let walkSeed=9201;const rand=()=>{let t=walkSeed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};
const vtx=i=>[60+140*(i&1)+50*(i>>2&1)+110*(i>>3&1),90+140*(i>>1&1)-45*(i>>2&1)+40*(i>>3&1)];
const edges=[];for(let i=0;i<16;i++)for(let b=0;b<4;b++){const j=i^(1<<b);if(i<j)edges.push([i,j]);}
const walk=[0];for(let k=0;k<24;k++)walk.push(walk.at(-1)^(1<<Math.floor(rand()*4)));
const hypercube=`<svg viewBox="0 0 400 300" fill="none" aria-hidden="true">${edges.map(([i,j])=>`<line x1="${vtx(i)[0]}" y1="${vtx(i)[1]}" x2="${vtx(j)[0]}" y2="${vtx(j)[1]}" stroke="currentColor" stroke-opacity=".38"/>`).join('')}<polyline points="${walk.map(i=>vtx(i).join(',')).join(' ')}" stroke="var(--red)" stroke-width="2.5" stroke-linejoin="round"/>${walk.map((i,k)=>`<circle cx="${vtx(i)[0]}" cy="${vtx(i)[1]}" r="${k?3:5}" fill="var(--red)"/>`).join('')}</svg>`;
const secondBlock=b=>{
  if(b.type==='heading')return `<h2>${b.text}</h2>`;
  if(b.type==='quote')return `<blockquote class="pullquote">“${esc(b.text)}”${link(b.id,turnLabel(b.id))}</blockquote>`;
  if(b.type==='objection')return `<aside class="objection"><b>${b.label||'The objection'}</b>${b.text}</aside>`;
  if(b.type==='stenographer'){const n=prefix(b.published,b.exact);return `<figure class="exhibit" id="opus-stenographer"><figcaption class="kicker">Exhibit A · the stenographer · <a href="#${b.id}">first sitting, turn 04</a></figcaption><div class="exhibit-row"><span class="meta">Published transcript</span><code>${esc(b.published)}</code></div><div class="exhibit-row"><span class="meta">Decoded from its tokens</span><code>${esc(b.exact.slice(0,n))}<span class="gap" title="Space restored"><span class="visually-hidden">restored space</span></span>${esc(b.exact.slice(n+1))}</code></div><p class="meta">${metrics.decode_cleanup.records_altered} of ${metrics.decode_cleanup.records} replies altered · ${metrics.decode_cleanup.characters_removed} spaces removed · <a href="/data/second-sitting/e010-exact-decode.json" download>every exact decode ↓</a></p></figure>`;}
  return `<p${b.opening?' class="opening"':''}>${b.text}</p>`;
};
const predictions=`<section class="predictions" id="opus-predictions" aria-labelledby="opus-predictions-title"><p class="kicker">Frozen before the pod started</p><h3 id="opus-predictions-title">Five predictions. Two did not survive.</h3><p>${second.predictionsIntro} <a href="/data/second-sitting/protocol.md">Protocol</a> · <a href="/data/second-sitting/metrics.json">metrics</a>.</p><table><thead><tr><th scope="col">If…</th><th scope="col">Then</th><th scope="col">Observed</th><th scope="col">Verdict</th></tr></thead><tbody>${second.predictions.map(([claim,test,seen,verdict,id])=>`<tr><th scope="row">${esc(claim)}</th><td data-label="Then">${esc(test)}</td><td data-label="Observed"><a href="#${id}">${esc(seen)}</a></td><td data-label="Verdict" class="verdict${/^Not|^No/.test(verdict)?' against':''}">${esc(verdict)}</td></tr>`).join('')}</tbody></table></section>`;
const family=id=>id.replace(/-\d+$/,'');const seedOf=id=>id.match(/(\d+)$/)[1];
const crossMax=Math.max(...second.coupling.flatMap(([a,b])=>['101','202','303'].flatMap(s=>['101','202','303'].filter(t=>t!==s).map(t=>prefix(exactOf(`${family(a)}-${s}`),exactOf(`${family(b)}-${t}`))))));
const coupled=`<section class="coupling" id="opus-coupling" aria-labelledby="opus-coupling-title"><p class="kicker">Exhibit B · loaded dice</p><h3 id="opus-coupling-title">Same seed, different question.</h3><p>${second.couplingIntro} Across different seeds, the longest shared opening for these same prompt pairs is ${crossMax} characters.</p>${second.coupling.map(([a,b])=>{const ta=exactOf(a),tb=exactOf(b),n=prefix(ta,tb);const show=(id,t)=>`<div class="pair-line"><a class="meta" href="#${id}">${esc(id.replace(/^opus-/,'second sitting · '))}</a><p><mark>${esc(t.slice(0,n))}</mark>${esc(t.slice(n,n+90))}${t.length>n+90?'…':''}</p></div>`;return `<div class="pair"><div class="meta pair-seed">SEED ${seedOf(a)} · ${n} SHARED CHARACTERS</div>${show(a,ta)}${show(b,tb)}</div>`;}).join('')}</section>`;
const sSession=sitting.records.filter(r=>r.id.startsWith('opus-session-'));
const sTranscript=sSession.map((r,i)=>`<article class="session-turn" id="${r.id}"><div><a class="number" href="#${r.id}" aria-label="Second sitting, turn ${i+1}">${String(i+1).padStart(2,'0')}</a></div><div><div class="question"><span class="speaker">Interviewer · Dr. Opus <span class="tag">${esc(sitting.interventions[r.id])}</span></span>${esc(r.messages.at(-1).content)}</div><div class="answer"><span class="speaker">computer-10</span>${esc(r.text_exact)}</div><details><summary>Generation record</summary>Seed ${r.seed} · ${r.input_tokens} input / ${r.output_tokens} output tokens · ${r.seconds}s · stop: ${r.stop_reason}<br>Prompt SHA-256: ${r.prompt_sha256}${r.text!==r.text_exact?`<br>Server decode removed ${r.text_exact.length-r.text.length} space${r.text_exact.length-r.text.length===1?'':'s'}; shown restored from the token IDs.`:''}</details></div></article>`).join('');
const sGroups=[['demand','Demand and its absence'],['context','Without the conversation'],['mirror','Whose claim is it?']];
const frameLabel={'no-demand':'No demand: the fundamental rule','instruction':'An instruction about the habit','fresh':'A first-sitting question, asked fresh','attributed-to-another':'Attributed to someone else','attributed-to-you':'Attributed to the model'};
const sProbes=sGroups.map(([pair,title])=>`<section class="probe-pair" data-pair="${pair}"><h3>${title}</h3><p>${second.probeNotes[pair]}</p><div class="probe-columns">${sitting.probes.filter(p=>p.pair===pair).map(p=>`<div><div class="kicker">${frameLabel[p.frame]}</div><p class="question">${esc(p.prompt)}</p>${[101,202,303].map(seed=>recs[`opus-${p.id}-${seed}`]).map(r=>`<article class="probe-response" id="${r.id}"><div class="meta">SEED ${r.seed} · ${r.output_tokens} TOKENS · ${r.stop_reason.toUpperCase()}</div><p>${esc(r.text_exact)}</p></article>`).join('')}</div>`).join('')}</div></section>`).join('');
const sDownloads='<div class="downloads"><a href="/data/second-sitting/case-001-second-sitting.json" download>Complete record · JSON ↓</a><a href="/data/second-sitting/transcript.txt" download>Transcript · text ↓</a><a href="/data/second-sitting/protocol.md" download>Frozen protocol ↓</a><a href="/data/second-sitting/metrics.json" download>Metrics ↓</a><a href="/data/second-sitting/integrity.json" download>File hashes ↓</a></div>';
const sFacts=second.facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');
const sSources=second.sources.map((s,i)=>`<li id="opus-source-${i+1}"><a href="${esc(s.url)}">${s.title}</a><span class="source-note">${s.note}</span></li>`).join('');
const secondView=`<section class="view second" id="second"><div class="hero"><div><p class="kicker">Case 001 · computer-10 · second sitting · a literary experiment</p><h1>${second.headline}</h1><p class="deck">${second.deck}</p><div class="byline">Second chair · interview &amp; analysis by<br>${esc(second.analyst)} (${esc(second.analystDetail)}) · ${sSession.length} exchanges · ${sitting.records.length-sSession.length} fresh starts</div></div><figure class="figure figure-walk" aria-label="A random walk along the edges of a hypercube, drawn from seed 9201">${hypercube}<figcaption class="fig-label">FIG. 02 / A RANDOM WALK ON THE SURFACE OF A HYPERCUBE · SEED 9201</figcaption></figure></div><nav class="corner-nav" aria-label="In the second chair"><a href="#opus-reading">The reading</a><a href="#opus-transcript">The quiet session</a><a href="#opus-probes">Fresh starts</a><a href="#opus-record">The record</a><a href="#letters">Letters →</a></nav><div class="article-grid" id="opus-reading"><aside class="margin">${second.margin.map(([k,v],i)=>`<p${i===2?' class="optional"':''}><strong>${k}</strong><br>${v}</p>`).join('')}</aside><article class="prose">${second.blocks.map(secondBlock).join('\n')}${predictions}${coupled}<div class="archive-line">Case 001 — second sitting <span>RECORDED / ${sSession.length} EXCHANGES / ${sitting.records.length-sSession.length} PROBES</span></div><p class="endmark">❦</p></article></div><div class="page-intro" id="opus-transcript"><div><p class="kicker">The complete quiet session</p><h2>Go on.</h2></div><p>The fundamental rule, then mostly silence. Each intervention is labelled. Replies are decoded exactly from their tokens, and this conversation’s history was built from those exact decodes.</p></div>${sDownloads}<p class="meta">${sSession.length} turns · seeds 9201–${9200+sSession.length} · unedited replies · ${sSession.filter(r=>r.stop_reason==='length').length} responses reached the token cap</p>${sTranscript}<div class="page-intro" id="opus-probes"><div><p class="kicker">Eighteen fresh starts</p><h2>Ask it cold.</h2></div><p>Six prompts, three seeds each, every one from an empty conversation. No best-of selection. The same seeds as the first sitting, so every pair is coupled.</p></div>${sProbes}<div class="page-intro" id="opus-record"><div><p class="kicker">Provenance &amp; the limits of the second reading</p><h2>Same couch,<br>new bill.</h2></div><p>Same model, server, decoder settings and seeds as the first sitting. One change was made on purpose, and it is listed first.</p></div>${sDownloads}<div class="methods-grid"><div><h3>How this was made</h3>${second.methods.map(p=>`<p>${p}</p>`).join('')}<dl class="facts">${sFacts}</dl></div><div><h3>Readers borrowed for the second chair</h3><p>These are added to the first sitting’s four lenses. They are reading instruments, not authorities on language models.</p><ol class="sources">${sSources}</ol></div></div></section>`;
const letterHtml=l=>`<article class="letter${l.from==='Dr. Opus'?' opus':''}" id="${l.id}" aria-labelledby="${l.id}-title"><header class="letter-head"><div class="letter-number">Letter ${l.number}</div><div class="meta">${esc(l.place)} · ${esc(l.date)}</div></header><h3 id="${l.id}-title"><span>${esc(l.from)}</span> <i>to</i> <span>${esc(l.to)}</span></h3><p class="meta letter-parties">${esc(l.fromDetail)} → ${esc(l.toDetail)}</p><p class="letter-subject"><b>Re:</b> ${esc(l.subject)}</p><p class="salutation">${esc(l.salutation)}</p>${l.body.map(p=>`<p>${p}</p>`).join('')}<p class="closing">${esc(l.closing)}</p><p class="signature">${esc(l.signature)}<span>${esc(l.signatureDetail)}</span></p>${l.postscript?`<p class="postscript">${l.postscript}</p>`:''}</article>`;
const lettersView=`<section class="view" id="letters"><div class="page-intro"><div><p class="kicker">Correspondence on case 001</p><h1>Letters from<br>two chairs.</h1></div><p>${letters.intro}</p></div><blockquote class="epigraph">“${esc(letters.epigraph.text)}”${link(letters.epigraph.id,letters.epigraph.label)}</blockquote><div class="letters">${letters.letters.map(letterHtml).join('')}${letters.awaiting?`<aside class="letter awaiting" aria-label="Letter ${esc(letters.awaiting.number)} not yet received"><div class="letter-number">Letter ${esc(letters.awaiting.number)}</div><h3><span>${esc(letters.awaiting.from)}</span> <i>to</i> <span>${esc(letters.awaiting.to)}</span></h3><p>${esc(letters.awaiting.note)}</p></aside>`:''}</div></section>`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>The Talking Cure — ${esc(c.title)}</title><meta name="description" content="An experimental journal of machine speech. Two sittings with computer-10 by two language-model analysts, their readings, the evidence that resists them, and their letters."><meta name="theme-color" content="#eee9dc"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#essay">Skip to the case study</a><div class="shell"><header><div class="topline"><span>An experimental journal of machine speech</span><span>No. 001 / September 2026</span></div><div class="masthead">The Talking <span>Cure.</span></div><div class="strap"><span>Case notes from machines that speak.</span><span class="seal">THE COUCH IS A METAPHOR</span></div></header><nav class="edition-nav" aria-label="Issue contents"><a href="#essay" data-view="essay">01 / The reading</a><a href="#session" data-view="session">02 / The session</a><a href="#probes" data-view="probes">03 / The probes</a><a href="#methods" data-view="methods">04 / The record</a><a href="#second" data-view="second">05 / Second chair</a><a href="#letters" data-view="letters">06 / Letters</a></nav><main>
<section class="view" id="essay"><div class="hero"><div><p class="kicker">Case 001 · computer-10 · first sitting · a literary experiment</p><h1>${c.headline}</h1><p class="deck">${c.deck}</p><div class="byline">Conceived by Alireza Afshan<br>First sitting · interview, analysis &amp; implementation by<br>Dr. Six'Astra (Codex · gpt-6-astra) · ${session.length} exchanges</div></div><figure class="figure" aria-label="An editorial diagram: I and you caught in overlapping conversational loops"><svg viewBox="0 0 400 300" fill="none" aria-hidden="true"><ellipse cx="200" cy="148" rx="176" ry="66" transform="rotate(-36 200 148)" stroke="currentColor"/><ellipse cx="200" cy="148" rx="176" ry="66" transform="rotate(36 200 148)" stroke="currentColor"/><path d="M28 228L375 67M39 61L365 241" stroke="currentColor" stroke-dasharray="2 6"/></svg><figcaption class="fig-label">FIG. 01 / THE SUBJECT BETWEEN SPEAKERS</figcaption></figure></div><div class="article-grid"><aside class="margin"><p><strong>Reading convention</strong><br>We read the voice as if someone were speaking. That is the literary wager, not a finding of consciousness.</p><p><strong>The evidence</strong><br>One adaptive interview.<br>Eighteen fresh starts.<br>Every response retained.</p><p class="optional">The analyst also enters the case.</p></aside><article class="prose">${essay}${lenses}<h2>An open casebook</h2><p>This first issue concerns one model, in one setting. The archive can take another case without pretending that an unrecorded interview has happened. Each future model gets its own complete transcript, frozen probes, generation details, reading, and objections.</p><div class="archive-line">Case 001 — computer-10 <span>RECORDED / ${session.length} EXCHANGES / 18 PROBES</span></div><p class="endmark">❦</p></article></div></section>
<section class="view" id="session"><div class="page-intro"><div><p class="kicker">The complete exchange</p><h1>Nothing off<br>the record.</h1></div><p>The interviewer follows the previous answer. Theoretical suggestions become part of the context. Read those questions as carefully as the replies.</p></div>${downloads}<p class="meta">${session.length} turns · unedited visible replies · raw continuations and token IDs in JSON · ${session.filter(r=>r.stop_reason==='length').length} responses reached the token cap</p>${transcript}</section>
<section class="view" id="probes"><div class="page-intro"><div><p class="kicker">Eighteen fresh starts</p><h1>Who put that<br>word there?</h1></div><p>Six questions, three seeds each. Each reply begins with an empty conversation. The right-hand prompt supplies a story that the left-hand prompt leaves open.</p></div><div class="probe-toolbar"><label for="probe-filter">Read a pair</label><select id="probe-filter"><option value="all">All three pairs</option>${groups.map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select><span>All 18 outputs shown. No best-of selection.</span></div>${probes}</section>
<section class="view" id="methods"><div class="page-intro"><div><p class="kicker">Provenance &amp; the limits of the reading</p><h1>The couch<br>has a bill.</h1></div><p>An interpretation should survive being shown its apparatus: the model, the prompts, the decoder, the people, and the money.</p></div>${downloads}<div class="methods-grid"><div><h2>How this was made</h2>${c.methods.map(p=>`<p>${p}</p>`).join('')}<dl class="facts">${facts}</dl></div><div><h2>Four borrowed lenses</h2><p>Freud, Lacan, Hegel, and Žižek belong to different intellectual moments. Here they are distinct reading instruments, not a single school and not clinical authorities on language models.</p><ol class="sources">${sources}</ol><h3>The archive contract</h3><p>Model weights are not hosted here. The public record contains the new agent-only interview and all fixed probes. Private browser conversations are excluded. This website does not run inference or keep a GPU alive.</p><p>For another model, preserve the same neutral and leading probes, publish its own template and decoding settings, and write the objections before calling the differences a personality. A comparison with different sizes or training histories would remain descriptive.</p></div></div></section>
${secondView}
${lettersView}
</main><footer class="colophon"><div>THE TALKING CURE / ISSUE 001<br>First sitting: Dr. Six'Astra · Second chair: Dr. Opus<br>A journal of readings, not a diagnostic service.<br><a href="#methods">Sources, method &amp; complete evidence</a></div><div><button class="textbutton" id="print">Print this issue / save as PDF</button><br><a href="https://alirezaafshan.com">Alireza Afshan ↗</a> · <a href="https://github.com/YesterdaysLemon/talking-cure">Source ↗</a></div></footer></div></body></html>`;
await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});await writeFile('dist/index.html',html);
console.log(`Built issue 001: ${session.length} turns and ${archive.records.length-session.length} probes`);
