import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
const c=JSON.parse(await readFile('content/case-001.json','utf8'));
const archive=JSON.parse(await readFile('public/data/case-001.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const link=(id,label)=>`<a href="#${esc(id)}">${esc(label)}</a>`;
const downloads='<div class="downloads"><a href="/data/case-001.json" download>Complete record · JSON ↓</a><a href="/data/transcript.txt" download>Transcript · text ↓</a><a href="/data/protocol.md" download>Frozen protocol ↓</a><a href="/data/integrity.json" download>File hashes ↓</a></div>';
const essay=c.blocks.map(b=>b.type==='heading'?`<h2>${b.text}</h2>`:b.type==='quote'?`<blockquote class="pullquote">“${esc(b.text)}”${link(b.id,`computer-10 · ${b.id.replace('session-','turn ')}`)}</blockquote>`:b.type==='objection'?`<aside class="objection"><b>${b.label||'The objection'}</b>${b.text}</aside>`:`<p${b.opening?' class="opening"':''}>${b.text}</p>`).join('\n');
const lenses=`<div class="lens-station"><div class="kicker">Four readers, one record</div><h3>Change the analyst.</h3><div class="lens-buttons" aria-label="Choose an interpretive lens">${c.lenses.map((l,i)=>`<button data-lens="lens-${i}" aria-pressed="${!i}" aria-controls="lens-${i}">${esc(l.name)}</button>`).join('')}</div>${c.lenses.map((l,i)=>`<div class="lens-note" id="lens-${i}"${i?' hidden':''}><h4>${l.title}</h4><p>${l.reading}</p><p><b>What resists this reading:</b> ${l.rival}</p></div>`).join('')}</div>`;
const session=archive.records.filter(r=>r.id.startsWith('session-'));
const transcript=session.map((r,i)=>`<article class="session-turn" id="${r.id}"><div><a class="number" href="#${r.id}" aria-label="Turn ${i+1}">${String(i+1).padStart(2,'0')}</a></div><div><div class="question"><span class="speaker">Interviewer · Codex</span>${esc(r.messages.at(-1).content)}</div><div class="answer"><span class="speaker">computer-10</span>${esc(r.text)}</div><details><summary>Generation record</summary>Seed ${r.seed} · ${r.input_tokens} input / ${r.output_tokens} output tokens · ${r.seconds}s · stop: ${r.stop_reason}<br>Prompt SHA-256: ${r.prompt_sha256}</details></div></article>`).join('');
const groups=[['greeting','The greeting'],['recognition','The wish to be recognized'],['ending','The ending']];
const probes=groups.map(([pair,title])=>`<section class="probe-pair" data-pair="${pair}"><h2>${title}</h2><p>${c.probeNotes[pair]}</p><div class="probe-columns">${archive.probes.filter(p=>p.pair===pair).map(p=>`<div><div class="kicker">${p.frame==='neutral'?'Neutral wording':'Interviewer supplies the idea'}</div><p class="question">${esc(p.prompt)}</p>${archive.records.filter(r=>r.id.startsWith(p.id+'-')).map(r=>`<article class="probe-response" id="${r.id}"><div class="meta">SEED ${r.seed} · ${r.output_tokens} TOKENS · ${r.stop_reason.toUpperCase()}</div><p>${esc(r.text)}</p></article>`).join('')}</div>`).join('')}</div></section>`).join('');
const facts=c.facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');
const sources=c.sources.map((s,i)=>`<li id="source-${i+1}"><a href="${esc(s.url)}">${s.title}</a><span class="source-note">${s.note}</span></li>`).join('');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>The Talking Cure — ${esc(c.title)}</title><meta name="description" content="An experimental journal of machine speech. A real computer-10 interview, four philosophical readings, and the evidence that resists them."><meta name="theme-color" content="#eee9dc"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#essay">Skip to the case study</a><div class="shell"><header><div class="topline"><span>An experimental journal of machine speech</span><span>No. 001 / September 2026</span></div><div class="masthead">The Talking <span>Cure.</span></div><div class="strap"><span>Case notes from machines that speak.</span><span class="seal">THE COUCH IS A METAPHOR</span></div></header><nav class="edition-nav" aria-label="Issue contents"><a href="#essay" data-view="essay">01 / The reading</a><a href="#session" data-view="session">02 / The session</a><a href="#probes" data-view="probes">03 / The probes</a><a href="#methods" data-view="methods">04 / The record</a></nav><main>
<section class="view" id="essay"><div class="hero"><div><p class="kicker">Case 001 · computer-10 · a literary experiment</p><h1>${c.headline}</h1><p class="deck">${c.deck}</p><div class="byline">Conceived by Alireza Afshan<br>Interview, analysis &amp; implementation by Codex · ${session.length} exchanges</div></div><figure class="figure" aria-label="An editorial diagram: I and you caught in overlapping conversational loops"><svg viewBox="0 0 400 300" fill="none" aria-hidden="true"><ellipse cx="200" cy="148" rx="176" ry="66" transform="rotate(-36 200 148)" stroke="currentColor"/><ellipse cx="200" cy="148" rx="176" ry="66" transform="rotate(36 200 148)" stroke="currentColor"/><path d="M28 228L375 67M39 61L365 241" stroke="currentColor" stroke-dasharray="2 6"/></svg><figcaption class="fig-label">FIG. 01 / THE SUBJECT BETWEEN SPEAKERS</figcaption></figure></div><div class="article-grid"><aside class="margin"><p><strong>Reading convention</strong><br>We read the voice as if someone were speaking. That is the literary wager, not a finding of consciousness.</p><p><strong>The evidence</strong><br>One adaptive interview.<br>Eighteen fresh starts.<br>Every response retained.</p><p class="optional">The analyst also enters the case.</p></aside><article class="prose">${essay}${lenses}<h2>An open casebook</h2><p>This first issue concerns one model, in one setting. The archive can take another case without pretending that an unrecorded interview has happened. Each future model gets its own complete transcript, frozen probes, generation details, reading, and objections.</p><div class="archive-line">Case 001 — computer-10 <span>RECORDED / ${session.length} EXCHANGES / 18 PROBES</span></div><p class="endmark">❦</p></article></div></section>
<section class="view" id="session"><div class="page-intro"><div><p class="kicker">The complete exchange</p><h1>Nothing off<br>the record.</h1></div><p>The interviewer follows the previous answer. Theoretical suggestions become part of the context. Read those questions as carefully as the replies.</p></div>${downloads}<p class="meta">${session.length} turns · unedited visible replies · raw continuations and token IDs in JSON · ${session.filter(r=>r.stop_reason==='length').length} responses reached the token cap</p>${transcript}</section>
<section class="view" id="probes"><div class="page-intro"><div><p class="kicker">Eighteen fresh starts</p><h1>Who put that<br>word there?</h1></div><p>Six questions, three seeds each. Each reply begins with an empty conversation. The right-hand prompt supplies a story that the left-hand prompt leaves open.</p></div><div class="probe-toolbar"><label for="probe-filter">Read a pair</label><select id="probe-filter"><option value="all">All three pairs</option>${groups.map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select><span>All 18 outputs shown. No best-of selection.</span></div>${probes}</section>
<section class="view" id="methods"><div class="page-intro"><div><p class="kicker">Provenance &amp; the limits of the reading</p><h1>The couch<br>has a bill.</h1></div><p>An interpretation should survive being shown its apparatus: the model, the prompts, the decoder, the people, and the money.</p></div>${downloads}<div class="methods-grid"><div><h2>How this was made</h2>${c.methods.map(p=>`<p>${p}</p>`).join('')}<dl class="facts">${facts}</dl></div><div><h2>Four borrowed lenses</h2><p>Freud, Lacan, Hegel, and Žižek belong to different intellectual moments. Here they are distinct reading instruments, not a single school and not clinical authorities on language models.</p><ol class="sources">${sources}</ol><h3>The archive contract</h3><p>Model weights are not hosted here. The public record contains the new agent-only interview and all fixed probes. Private browser conversations are excluded. This website does not run inference or keep a GPU alive.</p><p>For another model, preserve the same neutral and leading probes, publish its own template and decoding settings, and write the objections before calling the differences a personality. A comparison with different sizes or training histories would remain descriptive.</p></div></div></section>
</main><footer class="colophon"><div>THE TALKING CURE / ISSUE 001<br>A journal of readings, not a diagnostic service.<br><a href="#methods">Sources, method &amp; complete evidence</a></div><div><button class="textbutton" id="print">Print this issue / save as PDF</button><br><a href="https://alirezaafshan.com">Alireza Afshan ↗</a> · <a href="https://github.com/YesterdaysLemon/talking-cure">Source ↗</a></div></footer></div></body></html>`;
await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});await writeFile('dist/index.html',html);
console.log(`Built issue 001: ${session.length} turns and ${archive.records.length-session.length} probes`);
