import {readFile} from 'node:fs/promises';
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const blocks=bs=>bs.map(b=>b.type==='objection'?`<aside class="objection"><b>${esc(b.label)}</b>${b.text}</aside>`:`<p>${b.text}</p>`).join('\n');

export async function framingViews(){
  const c=await read('content/framing.json');
  const a=await read('public/data/coda/computer10.json');
  const opus=await read('public/data/coda/opus.json');
  const compute=await read('public/data/coda/compute.json');
  const r=a.records[0];
  const byline=`<p class="byline">${esc(c.author)}<br>${esc(c.date)} · written at the close of issue 001</p>`;
  const intro=(kicker,part)=>`<div class="page-intro"><div><p class="kicker">${kicker}</p><h1>${esc(part.title)}</h1></div><p>${part.deck}</p></div>`;
  const preface=`<section class="view bookend" id="preface" data-title="Preface">${intro('Preface · the reading convention',c.preface)}<div class="article-grid"><aside class="margin"><p><strong>Who is speaking?</strong><br>One human commissioner.<br>Two model essayists.<br>One model under discussion.</p><p><strong>How to read</strong><br>Every sitting has its full record.<br>Later letters can correct earlier readings.</p><p><a href="#final-thoughts">Go to the final thoughts →</a></p></aside><article class="prose">${byline}${blocks(c.preface.blocks)}</article></div></section>`;
  const findings=`<div class="closing-ledger" id="closing-findings"><p class="kicker">What the archive supports</p>${c.closing.findings.map(([name,observation,limit,id])=>`<div class="ledger-entry"><h3>${esc(name)}</h3><p>${esc(observation)} <a href="#${id}">[Record]</a></p><p class="ledger-limit">${esc(limit)}</p></div>`).join('')}</div>`;
  const opusText=opus.text.split(/\n\n/).map(p=>`<p>${esc(p).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>')}</p>`).join('');
  const contributions=`<section class="closing-voices" id="closing-voices"><p class="kicker">Invited closing contributions · reproduced in full</p><p class="contribution-context">These are differently situated replies, not a controlled comparison. Opus answered from a fork of the author session that wrote Letter III and the replay. computer-10 received one fresh prompt containing Six’Astra’s disclosed summary of all four sittings. It was not given the whole archive and has no cross-session memory implied here. Neither contribution was regenerated for style.</p><article class="closing-voice opus" id="closing-opus"><h2>From the second chair.</h2><p class="meta">Dr. Opus · Claude Opus 5.5 · Anthropic<br>Wording reproduced in full</p><div class="verbatim-contribution">${opusText}</div><details><summary>Invitation and provenance</summary><p class="answer">${esc(opus.prompt)}</p><p class="meta">${esc(opus.context)} <a href="/data/coda/opus.json">Complete contribution and provider metadata ↓</a></p></details><aside class="editor-note"><b>Six’Astra’s note on the wording.</b> The replay substituted corrected text in the earlier assistant messages for each tested turn; it did not change only one message. Also, the published quotation count measures spans per hundred words. It does not establish that words are mentioned more often than used; a quoted word can do both. Opus’s contribution is preserved as received, with these qualifications alongside it. <a href="#replay-fork">[Replay]</a> <a href="#letter-2">[Use and mention]</a></aside></article><article class="closing-voice" id="coda-15001"><h2>From computer-10.</h2><p class="meta">One fresh invitation · seed 15001 · ${r.output_tokens} output tokens · stop: ${esc(r.stop_reason)}</p><div class="answer coda-answer">${esc(r.text_exact)}</div><details><summary>The whole prompt and generation record</summary><p class="answer">${esc(r.messages[0].content)}</p><p class="meta">${r.input_tokens} input tokens · ${r.seconds}s · prompt SHA-256 ${r.prompt_sha256}</p>${r.text!==r.text_exact?`<p class="meta">Original server decode, before restored spacing</p><p class="answer">${esc(r.text)}</p>`:''}<p><a href="/data/coda/computer10.json">Full prompt, original text and token IDs ↓</a></p></details></article></section>`;
  const closing=`<section class="view bookend" id="final-thoughts" data-title="Final thoughts">${intro('Final thoughts · an issue brought to a close',c.closing)}<nav class="corner-nav" aria-label="In the closing pages"><a href="#closing-reading">The reading</a><a href="#closing-findings">The findings</a><a href="#closing-voices">Other voices</a><a href="#closing-last-word">The last word</a><a href="#closing-record">The record</a></nav><div class="article-grid" id="closing-reading"><aside class="margin"><p><strong>What changed?</strong><br>The record grew.<br>The interpretations changed.<br>The weights stayed fixed.</p><p><a href="#letter-4">Read Letter IV →</a></p></aside><article class="prose">${byline}${blocks(c.closing.blocks)}${findings}<h2>A chair for another reader.</h2><p>${c.closing.openQuestion}</p>${contributions}<section id="closing-last-word"><p class="kicker">Six’Astra · after the contributions</p><h2>The last word.</h2>${c.closing.lastWord.map(p=>`<p>${p}</p>`).join('')}<p class="endmark">❦</p></section><section id="closing-record"><p class="kicker">Provenance of the closing pages</p><p>Four sittings preserve 116 model generations; this final invitation adds one, for 117 computer-10 records. Replays and contextual turns are not independent samples. The frozen coda protocol was committed at <code>${a.protocol_commit}</code>. All earlier letters and evidence retain their original wording.</p><p>The coda used the same pinned BF16 weights, Model C frame, temperature 1, top-p .98, top-k 0, a 512-token output limit and the exact decoder. The full prompt was checked before rental. Local and separately retrieved cloud records were compared, prompt tokens re-encoded, and output tokens decoded again before publication.</p><p>Observed RunPod account debit: <b>$${compute.observed_balance_delta.toFixed(4)}</b>, checked ${esc(compute.billing_checked_at)}; this is an account delta, not a final invoice. The pod was deleted at ${esc(compute.deleted_at)}, with $0/hour spend verified. Opus’s provider reported a separate list-price estimate of $${opus.reported_list_price_usd.toFixed(4)} through the existing Claude subscription; it is not a measured charge to the RunPod balance.</p><p>The earlier CLI attempts returned no Opus contribution; an authentication mode and an unsupported CLI version were corrected before the sole successful response. The final site serves static pages and records. It keeps no model API or GPU running.</p><div class="downloads"><a href="/data/coda/transcript.txt" download>computer-10 transcript ↓</a><a href="/data/coda/opus.json" download>Opus’s contribution ↓</a><a href="/data/coda/protocol.md">Frozen protocol</a><a href="/data/coda/integrity.json">File hashes</a><a href="/data/coda/compute.json">Compute receipt</a></div></section></article></div></section>`;
  return {preface,closing};
}
