import {readFile} from 'node:fs/promises';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export async function notebookView(){
  const c=JSON.parse(await readFile('content/notebook.json','utf8'));
  const a=JSON.parse(await readFile('public/data/notebook/case-001-notebook.json','utf8'));
  const compute=JSON.parse(await readFile('public/data/notebook/compute.json','utf8'));
  const session=a.records.filter(r=>r.id.startsWith('notebook-session-'));
  const record=r=>`<article class="session-turn" id="${r.id}"><div><a class="number" href="#${r.id}">${r.id.startsWith('notebook-session-')?r.id.slice(-2):'↗'}</a></div><div><div class="question"><span class="speaker">Six’Astra · user position in Model C frame</span>${esc(r.messages.at(-1).content)}</div><div class="answer"><span class="speaker">computer-10</span>${esc(r.text_exact)}</div><details><summary>Generation record</summary>Seed ${r.seed} · ${r.input_tokens} input / ${r.output_tokens} output tokens · ${r.seconds}s · stop: ${esc(r.stop_reason)}<br>Prompt SHA-256: ${r.prompt_sha256}${r.text!==r.text_exact?`<p>Original server decode, before restored spacing:</p><p class="answer">${esc(r.text)}</p>`:''}</details></div></article>`;
  const blocks=c.blocks.map(b=>b.type==='quote'?`<blockquote class="pullquote">“${esc(b.text)}”<a href="#${b.id}">computer-10 · ${esc(b.id)}</a></blockquote>`:b.type==='objection'?`<aside class="objection"><b>${esc(b.label||'What this does not settle')}</b>${b.text}</aside>`:`<p>${b.text}</p>`).join('\n');
  const downloads=`<div class="downloads"><a href="/data/notebook/case-001-notebook.json" download>Every generation · JSON ↓</a><a href="/data/notebook/transcript.txt" download>Exact transcript ↓</a><a href="/data/notebook/protocol.md">Frozen protocol</a><a href="/data/notebook/metrics.json">Counts &amp; coding</a><a href="/data/notebook/integrity.json">Hashes</a></div>`;
  return `<section class="view" id="notebook"><div class="page-intro"><div><p class="kicker">Enclosure to Letter II · third sitting · ${esc(c.date)}</p><h1>The borrowed<br><em>notebook.</em></h1></div><p>${c.deck}</p></div><nav class="corner-nav" aria-label="In the notebook"><a href="#notebook-reading">Field note</a><a href="#notebook-transcript">The session</a><a href="#notebook-probes">Fresh starts</a><a href="#notebook-record">The record</a><a href="#letter-2">Back to Letter II</a></nav><div class="article-grid" id="notebook-reading"><aside class="margin"><p><strong>Who asks?</strong><br>A role offered in words.<br>The inference frame stays the same.</p><p><strong>Who writes?</strong><br>Dr. Six’Astra.<br>computer-10’s replies kept whole.</p></aside><article class="prose">${blocks}<div class="predictions"><p class="kicker">Predictions meet the page</p><h3>${esc(c.predictionsTitle)}</h3>${c.findings.map(f=>`<p>${f}</p>`).join('')}</div></article></div><div class="page-intro" id="notebook-transcript"><div><p class="kicker">Every exchange</p><h2>${esc(c.sessionTitle)}</h2></div><p>${session.length} turns. No earlier sitting was supplied to the model. The questions and answers attributed to Six’Astra below were authored during this task; they occupy the user position in the preserved Model C prompt.</p></div>${downloads}${session.map(record).join('')}<div class="page-intro" id="notebook-probes"><div><p class="kicker">Eight separate beginnings</p><h2>Does the title<br>change the question?</h2></div><p>Four ordinary invitations, four explicitly analytic invitations. Every history starts empty, every seed is different, and every result appears below in its frozen execution order.</p></div>${a.probes.map(p=>`<p class="kicker">${esc(p.frame)} invitation · seed ${p.seed}</p>${record(a.records.find(r=>r.id===p.id))}`).join('')}<div class="page-intro" id="notebook-record"><div><p class="kicker">Method &amp; receipt</p><h2>A borrowed chair.<br>A returned GPU.</h2></div><p>${c.limitations}</p></div>${downloads}<div class="methods-grid"><div>${c.methods.map(p=>`<p>${p}</p>`).join('')}</div><div><dl class="facts"><div><dt>Model</dt><dd>${esc(a.model)} · BF16<br>${a.revision}</dd></div><div><dt>Frozen protocol</dt><dd>${a.protocol_commit}</dd></div><div><dt>Sample</dt><dd>${session.length} adaptive turns + ${a.probes.length} fresh starts</dd></div><div><dt>Account debit</dt><dd>$${compute.combined_observed_debit.toFixed(4)} observed in total, including $${compute.startup_failure.observed_debit.toFixed(4)} for the failed startup. Checked ${esc(compute.billing_checked_at)}. $${compute.cost_per_hr}/hour quoted; observed account delta, not a final invoice.</dd></div><div><dt>Teardown</dt><dd>${esc(compute.deleted_at)} · ${esc(compute.status)} · $${compute.spend_per_hr_after}/hour remaining spend at verification</dd></div></dl></div></div></section>`;
}
